Repository comma-journal/comma, pull requests merged in 2025-09, with the labels that each got.

#11 feat: 일기 작성 기능 구현 1차 완료
  Frontend/commma/App.tsx
  Frontend/commma/components/BottomTabNavigator.js
  Frontend/commma/components/EmotionGrid.js
  Frontend/commma/components/EmotionModal.js
  Frontend/commma/components/TextSelector.js
  Frontend/commma/data/emotionsData.js
  Frontend/commma/package-lock.json
  Frontend/commma/package.json
  Frontend/commma/pages/DiaryDetail.js
  Frontend/commma/pages/DiaryEditor.js
  Frontend/commma/pages/EmotionSelector.js
  Frontend/commma/pages/Write.js
  Frontend/commma/styles/DiaryDetailStyles.js
  Frontend/commma/styles/DiaryEditorStyles.js
  Frontend/commma/styles/EmotionSelectorStyles.js
  Frontend/commma/styles/TextSelectorStyles.js
  Frontend/commma/styles/WriteStyles.js
  Frontend/commma/styles/components/EmotionGridStyles.js
  Frontend/commma/styles/components/EmotionModalStyles.js
Labels: feat

#12 feat: 메인페이지 디자인 작업 완료 및 ios 파일 수정
  Frontend/commma/assets/blanklogo.png
  Frontend/commma/assets/logo_main.svg
  Frontend/commma/components/BottomTabNavigator.js
  Frontend/commma/ios/Podfile.lock
  Frontend/commma/ios/commma.xcodeproj/project.pbxproj
  Frontend/commma/metro.config.js
  Frontend/commma/package-lock.json
  Frontend/commma/package.json
  Frontend/commma/pages/Home.js
  Frontend/commma/pages/HomeScreen.js
  Frontend/commma/styles/HomeScreenStyle.js
Labels: design

#14 fix: 일기 쓰기 중 하단바 숨김
  Frontend/commma/components/BottomTabNavigator.js
  Frontend/commma/pages/DiaryDetail.js
  Frontend/commma/pages/DiaryEditor.js
  Frontend/commma/pages/EmotionSelector.js
  Frontend/commma/pages/Write.js
Labels: feat

#15 Frontend
  Frontend/commma/App.tsx
  Frontend/commma/components/BottomTabNavigator.js
  Frontend/commma/ios/Podfile.lock
  Frontend/commma/pages/HomeScreen.js
  Frontend/commma/pages/LoginScreen.js
  Frontend/commma/pages/OnboardingScreen.js
  Frontend/commma/styles/HomeScreenStyle.js
Labels: refactor

#21 feat: 일기 작성 및 감정 선택 기능 통합 구현, 커스텀 디자인 알림 적용
  Frontend/commma/components/CustomAlert.js
  Frontend/commma/components/EmotionModal.js
  Frontend/commma/components/TextSelector.js
  Frontend/commma/hooks/useCustomAlert.js
  Frontend/commma/pages/DiaryDetail.js
  Frontend/commma/pages/EmotionSelector.js
  Frontend/commma/pages/LoginScreen.js
  Frontend/commma/pages/MyPage.js
  Frontend/commma/pages/OnboardingScreen.js
  Frontend/commma/pages/Write.js
  Frontend/commma/styles/DiaryDetailStyles.js
  Frontend/commma/styles/EmotionSelectorStyles.js
  Frontend/commma/styles/TextSelectorStyles.js
Labels: feat, refactor

#39 fix: 불필요 주석 및 콘솔 제거
  Frontend/commma/App.tsx
  Frontend/commma/api/config.js
  Frontend/commma/components/BottomTabNavigator.js
  Frontend/commma/components/CustomAlert.js
  Frontend/commma/components/EmotionGrid.js
  Frontend/commma/components/EmotionModal.js
  Frontend/commma/components/SplashScreen.js
  Frontend/commma/components/TextSelector.js
  Frontend/commma/hooks/useEmotionsData.js
  Frontend/commma/pages/DiaryDetail.js
  Frontend/commma/pages/DiaryEditor.js
  Frontend/commma/pages/EmotionSelector.js
  Frontend/commma/pages/HomeScreen.js
  Frontend/commma/pages/LoginScreen.js
  Frontend/commma/pages/MyPage.js
  Frontend/commma/pages/OnboardingScreen.js
  Frontend/commma/pages/Write.js
  Frontend/commma/styles/HomeScreenStyle.js
  Frontend/commma/styles/TextSelectorStyles.js
Labels: refactor

#41 feat(be): AI Comment 생성 로직 수정
  Backend/src/main/kotlin/kr/elroy/comma/ai/AiComment.kt
  Backend/src/main/resources/application.yaml
Labels: refactor
